
#  /home/akimov/desktop/wb/wb-edi/edi-doc-api/src/main/resources/schemas/fns/DP_INFSOOB_1_981_00_05_01_01.xsd

# Параметры вывода сгенерированных xml документов
output:
  # валидация сгенерированного XML документа [none | schema | schematron]
  post_validate: schema
  # прерывать выполнение при ошибке валидации
  fail_fast: true

# Глобальные настройки, применяемые ко всем генерируемым документам
global:

  # Шаблон имени файла для сохранения сгенерированного документа.
  output_filename: "2BM-{{ number(1000000000, 9999999999) }}-{{ number(1000000000, 9999999999) }}-{{ number(100000000000000000000, 999999999999999999999) }}"

  randomization:
    # вероятность добавления опциональных элементов
    probability: 1
    # ограничение максимального количества элементов
    max_occurs: 5

  # Переопределения значений тегов и атрибутов примитивных типов.
  # Ключ - строка или регулярное выражение.
  # Значение может быть строкой с опциональным использованием плейсхолдеров:
  # {{ function }} - подставит значение, предоставленное предопределенной функцией function.
  # Список доступных функций:
  # - file_name
  #
  # - last_name
  # - first_name
  # - middle_name
  # - address_text
  # - administrative_unit
  # - house_number
  # - city_name
  # - postcode
  # - company_name
  # - bank_name
  # - phone_number
  # - inn_fl
  # - inn_ul
  # - ogrn_ip
  # - ogrn_fl
  # - kpp
  # - snils_formatted
  #
  # - uuid
  # - number(A, B) - случайное число от A до B
  # - regex("pattern") - сгенерирует значение по указанному регулярному выражению
  # - TODO date("2010-01-01", "2025-01-01") - случайная дата в указанном диапазоне.
  #
  # {{ function | modifier }} - то же, но с модификатором [ global | local ], где
  # - global - будет использовано одно значение на всю генерацию.
  # - local - будет использовано одно значение в контексте одного документа.
  #
  # Порядок записей важен, будет выбрано первое подходящее переопределение.
  # Поиск по ключу происходит без учета регистра.
  value_override:
#    "^(ИдФайл|FileID)$": "{{ regex('\\d{2,5}') }}"       ## file_name
    "^(ИдФайл|FileID)$": "{{ number(1, 10) }}"       ## file_name
    "^(ВерсПрог|VersProg)$": "Xsd2Xml 0.1.0"
    "Фамилия":   "{{ last_name }}"
    "Имя":       "{{ first_name }}"
    "Отчество":  "{{ middle_name }}"
    "АдрТекст":  "{{ address_text }}"
    "Район":     "{{ administrative_unit }}"
    "Дом":       "{{ house_number }}"
    "Город":     "{{ city_name }}"
    "Индекс":    "{{ postcode }}"
    "НаимОрг":   "{{ company_name }}"
    "НаимБанк":  "{{ bank_name }}"
    "Тлф":       "{{ phone_number }}"
    "ИННФЛ":     "{{ inn_fl }}"
    "ИННЮЛ":     "{{ inn_ul }}"
    "^ОГРНИП$":  "{{ ogrn_ip }}"
    "^ОГРН$":    "{{ ogrn_fl }}"
    "КПП":       "{{ kpp }}"
    "СНИЛС":     "{{ snils_formatted }}"

# Переопределение глобальных настроек для определенных файлов
# Ключ - строка или регулярное выражение для поиска файла(ов).
# Порядок записей важен, будет выбрано первое подходящее переопределение.
# Поиск по ключу происходит без учета регистра.
specific:
  "DP_INFSOOB_1_981_00_05_01_01":
    randomization:
      max_occurs: 4
    value_override: {}
