## Пример конфигурации для генерации документов по форматам ФНС
global:
  source_filename: "^(?P<extracted>(ON|DP)_[A-Z0-9]*)_.*"
  output_filename: "{{ source_extracted }}_2BM-{{ number(1000000000, 9999999999) }}-{{ number(100000000, 999999999) }}-{{ number(100000000000000000000, 999999999999999999999) }}_2BM-{{ number(1000000000, 9999999999) }}-{{ number(100000000, 999999999) }}-{{ number(100000000000000000000, 999999999999999999999) }}_{{ date('2010-01-01', '2025-01-01') }}_{{ uuid }}"

  randomization:
    probability: 1
    min_occurs: 0
    max_occurs: 3
    min_length: 8
    max_length: 12
    min_inclusive: 0
    max_inclusive: 100000

  value_override:
    "^(ИдФайл|FileID)$": "{{ output_filename }}"
    "^(ВерсПрог|VersProg)$": "xmlgenerator 0.6.0"
    "Фамилия":   "{{ last_name('ru_RU') }}"
    "Имя":       "{{ first_name('ru_RU') }}"
    "Отчество":  "{{ middle_name('ru_RU') }}"
    "АдрТекст":  "{{ city('ru_RU') }}, {{ street('ru_RU') }}, д. {{ house_number('ru_RU') }}, кв. {{ number(1, 100) }}"
    "Район":     "{{ administrative_unit('ru_RU') }}"
    "Дом":       "{{ house_number('ru_RU') }}"
    "Город":     "{{ city('ru_RU') }}"
    "Корпус":    "{{ number(1, 20) }}"
    "Кварт":     "{{ number(1, 200) }}"
    "Улица":     "{{ street('ru_RU') }}"
    "Индекс":    "{{ postcode('ru_RU') }}"
    "НаимОрг":   "{{ company_name('ru_RU') }}"
    "НаимБанк":  "{{ bank_name('ru_RU') }}"
    "Тлф":       "{{ phone_number('ru_RU') }}"
    "ИННФЛ":     "{{ inn_fl }}"
    "ИННЮЛ":     "{{ inn_ul }}"
    "^ОГРНИП$":  "{{ ogrn_ip }}"
    "^ОГРН$":    "{{ ogrn_fl }}"
    "КПП":       "{{ kpp }}"
    "СНИЛС":     "{{ snils_formatted }}"
    "ЭлПочта":   "{{ email('ru_RU') }}"

specific:
  ".*":
    value_override:
      ОдомВыезд:   # reset
      ОдомЗаезд:   # reset
      ОдомПриемТС: # reset
      ОдомСдачТС:  # reset
      ПрИспКППКр:  # reset
      ДефИННЮЛ:    # reset
      ДефИННФЛ:    # reset
